### ISSUE TITLE
error while installing requirements

### ISSUE THREAD

**Issue by metalpandit** [shivamksharma/DevBrute#2]
im facing an issue while trying to install requirements 
<sudo pip3 install -r setup.py>
<**ERROR: Invalid requirement: 'import os, math, sys' (from line 1 of `setup.py)**>`

ps im on 
**Operating System: Kali GNU/Linux Rolling
            Kernel: Linux 5.10.0-kali3-amd64
      Architecture: x86-64**
    
![error Devbrute2021-05-03 20:56:01](https://user-images.githubusercontent.com/82305550/116873489-bcd05e00-ac52-11eb-91f7-af0942f202d5.png)

**Comment by zeeshantoor** [comment]
Same here!!

**Comment by mabdullah3** [comment]
same

**Comment by zyandro** [comment]
yeah manh

**Comment by gruz123** [comment]
same

**Comment by ReddyKousic** [comment]
same

**Comment by sahilalon** [comment]
I thing you should have to try this command: $python3 setup.py

if you get syntext error in line 49.
then just edit one line of code.
which is "chmod +x setup.py"

change it with this code :

os.system("chmod +x setup.py").

Hence your problem will be solve.
